graph LR
    subgraph Аудитория
        Пользователь(👤 Пользователь)
        Читатель(📖 Читатель)
    end

    subgraph Боты
        Бот(🤖 1 ... N)
    end

    subgraph Мастерская ботов
        Канал[@Botikot - Канал 📡]
        style Канал fill:#D3E4CD, stroke:#A3B18A, stroke-width:2px
        Блог(📑 Блог Telegraph.ph)
        Сообщество(💬 Группа ЛАМПА)
    end

    Пользователь --> Бот
    Бот --> Канал
    Канал --> Блог
    Блог <--> Читатель
    Канал --> Сообщество
